### ISSUE TITLE
Import all icons at once?

### ISSUE THREAD

**Issue by brettgibson5** [michaelbazos/angular-feather#1]
Will definitely be using a lot of these feather icons on a few of my Angular projects, was curious if there was a way to just add one line in app.module.ts to import icon set opposed to individually?

**Comment by michaelbazos** [comment]
Hi @brettgibson5 ,

No, because the library itself doesn't provide a "wrapper module" which would just export all icons.
This is on purpose, to avoid consumers importing all 240 icons as per version 3.2.2 and bloating their vendors script.

Of course, it would be not very nice to bloat `app.module.ts` with a lot of specific icons import. I'd suggest you create an `IconsModule` which contains all the icons you would like, and then you deal with your own `IconsModule` as a whole. The hierarchy of modules would be something like this:

```
AppModule
└── IconsModule
    ├── IconLogIn
    ├── IconLogOut
    ├── ...
    └── IconUser
```

The icons module only **exports** the symbols you want:

**icons.module.ts**
```
import { NgModule } from '@angular/core';

import { IconLogIn, IconLogOut, IconUser } from 'angular-feather';

@NgModule({
  exports: [
    IconLogIn,
    IconLogOut,
    IconUser
  ]
})
export class IconsModule { }
```

Does this help?

**Comment by brettgibson5** [comment]
Great, I will do this, thanks!
