### ISSUE TITLE
Unexpected Module

### ISSUE THREAD

**Issue by pdobrigkeit** [michaelbazos/angular-feather#7]
Hey, I am trying to use your module with a current Angular 5 and I am getting the following problem:

	Unexpected module 'IconCamera' declared by the module 'IconsModule'. Please add a @Pipe/@Directive/@Component annotation.

I reproduced it with a new stackblitz with current angular modules and I am pretty new to angular, so I have no idea right now, what could have changed.

https://stackblitz.com/edit/angular-i834ks?file=app%2Ficons%2Ficons.module.ts

**Comment by michaelbazos** [comment]
That's because the icons are modules themselves, this was necessary for proper AOT compilation, so they should be referenced in the `imports` property instead of the `declarations`.

So your `IconModule` would be like this:

```
const icons = [
  IconCamera
];

@NgModule({
  imports: icons,
  exports: icons
})
export class IconsModule { }
```

I noticed the demo linked from the readme was against a previous version of *angular-feather*, hence I'm responsible for the confusion :) It's updated now: [DEMO](https://stackblitz.com/edit/angular-feather?file=app%2Ficons%2Ficons.module.ts)

**Comment by pdobrigkeit** [comment]
Works great. Thanks for the quick reply
